[project]
name = "ghostbuilder"
type = "javascript"

[build]
command = "npm run build"
directory = ".next"

[site]
bucket = "./.next"
entry-point = "workers-site"

[env.production]
account_id = "<YOUR_ACCOUNT_ID>"
zone_id = "<YOUR_ZONE_ID>"
route = "ghostbuilder.yourdomain.com/*"
